# Funding links are being prepared.
# For now, follow the maintainer profile for updates and future support options.

custom:
  - "https://github.com/christopherrainnel"
  - "https://www.patreon.com/posts/standard-one-tip-152177425?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link"
